#!/bin/sh

alias ls="LC_COLLATE=C ls --color --group-directories-first"
alias ll="LC_COLLATE=C ls -alhF --time-style=+%Y-%m-%d\ %H:%m:%S"
# alias lla="ls -alhF --time-style=+%Y-%m-%d\ %H:%m:%S"
alias la="LC_COLLATE=C ls -ahF"

alias py="python3"
# alias pip=pip3

# alias composer="composer --ansi"
# alias artisan="php artisan --ansi"
# alias dep="dep --ansi"

alias bat="bat --color=always --theme="Monokai Extended""
alias batn="bat --style="changes,header""

## For My Proxy Tunnel
alias proxy-on="ssh -fN ssh-proxy-tunnel-gcp"
alias proxy-check="ssh -O check ssh-proxy-tunnel-gcp"
alias proxy-off="ssh -O exit ssh-proxy-tunnel-gcp"
